INSERT INTO business_type (name) VALUES ('Sole Trader');
INSERT INTO business_type (name) VALUES ('Partnership');
INSERT INTO business_type (name) VALUES ('Trust');
INSERT INTO business_type (name) VALUES ('Organisation');
INSERT INTO business_type (name) VALUES ('Corporation');
INSERT INTO business_type (name) VALUES ('Company');
INSERT INTO business_type (name) VALUES ('Family');
INSERT INTO business_type (name) VALUES ('Individual');

INSERT INTO country (iso2, name) VALUES ('AF', 'Afghanistan');
INSERT INTO country (iso2, name) VALUES ('AL', 'Albania');
INSERT INTO country (iso2, name) VALUES ('DZ', 'Algeria');
INSERT INTO country (iso2, name) VALUES ('DS', 'American Samoa');
INSERT INTO country (iso2, name) VALUES ('AD', 'Andorra');
INSERT INTO country (iso2, name) VALUES ('AO', 'Angola');
INSERT INTO country (iso2, name) VALUES ('AI', 'Anguilla');
INSERT INTO country (iso2, name) VALUES ('AQ', 'Antarctica');
INSERT INTO country (iso2, name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO country (iso2, name) VALUES ('AR', 'Argentina');
INSERT INTO country (iso2, name) VALUES ('AM', 'Armenia');
INSERT INTO country (iso2, name) VALUES ('AW', 'Aruba');
INSERT INTO country (iso2, name) VALUES ('AU', 'Australia');
INSERT INTO country (iso2, name) VALUES ('AT', 'Austria');
INSERT INTO country (iso2, name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO country (iso2, name) VALUES ('BS', 'Bahamas');
INSERT INTO country (iso2, name) VALUES ('BH', 'Bahrain');
INSERT INTO country (iso2, name) VALUES ('BD', 'Bangladesh');
INSERT INTO country (iso2, name) VALUES ('BB', 'Barbados');
INSERT INTO country (iso2, name) VALUES ('BY', 'Belarus');
INSERT INTO country (iso2, name) VALUES ('BE', 'Belgium');
INSERT INTO country (iso2, name) VALUES ('BZ', 'Belize');
INSERT INTO country (iso2, name) VALUES ('BJ', 'Benin');
INSERT INTO country (iso2, name) VALUES ('BM', 'Bermuda');
INSERT INTO country (iso2, name) VALUES ('BT', 'Bhutan');
INSERT INTO country (iso2, name) VALUES ('BO', 'Bolivia');
INSERT INTO country (iso2, name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO country (iso2, name) VALUES ('BW', 'Botswana');
INSERT INTO country (iso2, name) VALUES ('BV', 'Bouvet Island');
INSERT INTO country (iso2, name) VALUES ('BR', 'Brazil');
INSERT INTO country (iso2, name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO country (iso2, name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO country (iso2, name) VALUES ('BG', 'Bulgaria');
INSERT INTO country (iso2, name) VALUES ('BF', 'Burkina Faso');
INSERT INTO country (iso2, name) VALUES ('BI', 'Burundi');
INSERT INTO country (iso2, name) VALUES ('KH', 'Cambodia');
INSERT INTO country (iso2, name) VALUES ('CM', 'Cameroon');
INSERT INTO country (iso2, name) VALUES ('CA', 'Canada');
INSERT INTO country (iso2, name) VALUES ('CV', 'Cape Verde');
INSERT INTO country (iso2, name) VALUES ('KY', 'Cayman Islands');
INSERT INTO country (iso2, name) VALUES ('CF', 'Central African Republic');
INSERT INTO country (iso2, name) VALUES ('TD', 'Chad');
INSERT INTO country (iso2, name) VALUES ('CL', 'Chile');
INSERT INTO country (iso2, name) VALUES ('CN', 'China');
INSERT INTO country (iso2, name) VALUES ('CX', 'Christmas Island');
INSERT INTO country (iso2, name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO country (iso2, name) VALUES ('CO', 'Colombia');
INSERT INTO country (iso2, name) VALUES ('KM', 'Comoros');
INSERT INTO country (iso2, name) VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO country (iso2, name) VALUES ('CG', 'Republic of Congo');
INSERT INTO country (iso2, name) VALUES ('CK', 'Cook Islands');
INSERT INTO country (iso2, name) VALUES ('CR', 'Costa Rica');
INSERT INTO country (iso2, name) VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO country (iso2, name) VALUES ('CU', 'Cuba');
INSERT INTO country (iso2, name) VALUES ('CY', 'Cyprus');
INSERT INTO country (iso2, name) VALUES ('CZ', 'Czech Republic');
INSERT INTO country (iso2, name) VALUES ('DK', 'Denmark');
INSERT INTO country (iso2, name) VALUES ('DJ', 'Djibouti');
INSERT INTO country (iso2, name) VALUES ('DM', 'Dominica');
INSERT INTO country (iso2, name) VALUES ('DO', 'Dominican Republic');
INSERT INTO country (iso2, name) VALUES ('TP', 'East Timor');
INSERT INTO country (iso2, name) VALUES ('EC', 'Ecuador');
INSERT INTO country (iso2, name) VALUES ('EG', 'Egypt');
INSERT INTO country (iso2, name) VALUES ('SV', 'El Salvador');
INSERT INTO country (iso2, name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country (iso2, name) VALUES ('ER', 'Eritrea');
INSERT INTO country (iso2, name) VALUES ('EE', 'Estonia');
INSERT INTO country (iso2, name) VALUES ('ET', 'Ethiopia');
INSERT INTO country (iso2, name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO country (iso2, name) VALUES ('FO', 'Faroe Islands');
INSERT INTO country (iso2, name) VALUES ('FJ', 'Fiji');
INSERT INTO country (iso2, name) VALUES ('FI', 'Finland');
INSERT INTO country (iso2, name) VALUES ('FR', 'France');
INSERT INTO country (iso2, name) VALUES ('FX', 'France, Metropolitan');
INSERT INTO country (iso2, name) VALUES ('GF', 'French Guiana');
INSERT INTO country (iso2, name) VALUES ('PF', 'French Polynesia');
INSERT INTO country (iso2, name) VALUES ('TF', 'French Southern Territories');
INSERT INTO country (iso2, name) VALUES ('GA', 'Gabon');
INSERT INTO country (iso2, name) VALUES ('GM', 'Gambia');
INSERT INTO country (iso2, name) VALUES ('GE', 'Georgia');
INSERT INTO country (iso2, name) VALUES ('DE', 'Germany');
INSERT INTO country (iso2, name) VALUES ('GH', 'Ghana');
INSERT INTO country (iso2, name) VALUES ('GI', 'Gibraltar');
INSERT INTO country (iso2, name) VALUES ('GK', 'Guernsey');
INSERT INTO country (iso2, name) VALUES ('GR', 'Greece');
INSERT INTO country (iso2, name) VALUES ('GL', 'Greenland');
INSERT INTO country (iso2, name) VALUES ('GD', 'Grenada');
INSERT INTO country (iso2, name) VALUES ('GP', 'Guadeloupe');
INSERT INTO country (iso2, name) VALUES ('GU', 'Guam');
INSERT INTO country (iso2, name) VALUES ('GT', 'Guatemala');
INSERT INTO country (iso2, name) VALUES ('GN', 'Guinea');
INSERT INTO country (iso2, name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO country (iso2, name) VALUES ('GY', 'Guyana');
INSERT INTO country (iso2, name) VALUES ('HT', 'Haiti');
INSERT INTO country (iso2, name) VALUES ('HM', 'Heard and Mc Donald Islands');
INSERT INTO country (iso2, name) VALUES ('HN', 'Honduras');
INSERT INTO country (iso2, name) VALUES ('HK', 'Hong Kong');
INSERT INTO country (iso2, name) VALUES ('HU', 'Hungary');
INSERT INTO country (iso2, name) VALUES ('IS', 'Iceland');
INSERT INTO country (iso2, name) VALUES ('IN', 'India');
INSERT INTO country (iso2, name) VALUES ('IM', 'Isle of Man');
INSERT INTO country (iso2, name) VALUES ('ID', 'Indonesia');
INSERT INTO country (iso2, name) VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO country (iso2, name) VALUES ('IQ', 'Iraq');
INSERT INTO country (iso2, name) VALUES ('IE', 'Ireland');
INSERT INTO country (iso2, name) VALUES ('IL', 'Israel');
INSERT INTO country (iso2, name) VALUES ('IT', 'Italy');
INSERT INTO country (iso2, name) VALUES ('CI', 'Ivory Coast');
INSERT INTO country (iso2, name) VALUES ('JE', 'Jersey');
INSERT INTO country (iso2, name) VALUES ('JM', 'Jamaica');
INSERT INTO country (iso2, name) VALUES ('JP', 'Japan');
INSERT INTO country (iso2, name) VALUES ('JO', 'Jordan');
INSERT INTO country (iso2, name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO country (iso2, name) VALUES ('KE', 'Kenya');
INSERT INTO country (iso2, name) VALUES ('KI', 'Kiribati');
INSERT INTO country (iso2, name) VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO country (iso2, name) VALUES ('KR', 'Korea, Republic of');
INSERT INTO country (iso2, name) VALUES ('XK', 'Kosovo');
INSERT INTO country (iso2, name) VALUES ('KW', 'Kuwait');
INSERT INTO country (iso2, name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO country (iso2, name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO country (iso2, name) VALUES ('LV', 'Latvia');
INSERT INTO country (iso2, name) VALUES ('LB', 'Lebanon');
INSERT INTO country (iso2, name) VALUES ('LS', 'Lesotho');
INSERT INTO country (iso2, name) VALUES ('LR', 'Liberia');
INSERT INTO country (iso2, name) VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO country (iso2, name) VALUES ('LI', 'Liechtenstein');
INSERT INTO country (iso2, name) VALUES ('LT', 'Lithuania');
INSERT INTO country (iso2, name) VALUES ('LU', 'Luxembourg');
INSERT INTO country (iso2, name) VALUES ('MO', 'Macau');
INSERT INTO country (iso2, name) VALUES ('MK', 'North Macedonia');
INSERT INTO country (iso2, name) VALUES ('MG', 'Madagascar');
INSERT INTO country (iso2, name) VALUES ('MW', 'Malawi');
INSERT INTO country (iso2, name) VALUES ('MY', 'Malaysia');
INSERT INTO country (iso2, name) VALUES ('MV', 'Maldives');
INSERT INTO country (iso2, name) VALUES ('ML', 'Mali');
INSERT INTO country (iso2, name) VALUES ('MT', 'Malta');
INSERT INTO country (iso2, name) VALUES ('MH', 'Marshall Islands');
INSERT INTO country (iso2, name) VALUES ('MQ', 'Martinique');
INSERT INTO country (iso2, name) VALUES ('MR', 'Mauritania');
INSERT INTO country (iso2, name) VALUES ('MU', 'Mauritius');
INSERT INTO country (iso2, name) VALUES ('TY', 'Mayotte');
INSERT INTO country (iso2, name) VALUES ('MX', 'Mexico');
INSERT INTO country (iso2, name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO country (iso2, name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO country (iso2, name) VALUES ('MC', 'Monaco');
INSERT INTO country (iso2, name) VALUES ('MN', 'Mongolia');
INSERT INTO country (iso2, name) VALUES ('ME', 'Montenegro');
INSERT INTO country (iso2, name) VALUES ('MS', 'Montserrat');
INSERT INTO country (iso2, name) VALUES ('MA', 'Morocco');
INSERT INTO country (iso2, name) VALUES ('MZ', 'Mozambique');
INSERT INTO country (iso2, name) VALUES ('MM', 'Myanmar');
INSERT INTO country (iso2, name) VALUES ('NA', 'Namibia');
INSERT INTO country (iso2, name) VALUES ('NR', 'Nauru');
INSERT INTO country (iso2, name) VALUES ('NP', 'Nepal');
INSERT INTO country (iso2, name) VALUES ('NL', 'Netherlands');
INSERT INTO country (iso2, name) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO country (iso2, name) VALUES ('NC', 'New Caledonia');
INSERT INTO country (iso2, name) VALUES ('NZ', 'New Zealand');
INSERT INTO country (iso2, name) VALUES ('NI', 'Nicaragua');
INSERT INTO country (iso2, name) VALUES ('NE', 'Niger');
INSERT INTO country (iso2, name) VALUES ('NG', 'Nigeria');
INSERT INTO country (iso2, name) VALUES ('NU', 'Niue');
INSERT INTO country (iso2, name) VALUES ('NF', 'Norfolk Island');
INSERT INTO country (iso2, name) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO country (iso2, name) VALUES ('NO', 'Norway');
INSERT INTO country (iso2, name) VALUES ('OM', 'Oman');
INSERT INTO country (iso2, name) VALUES ('PK', 'Pakistan');
INSERT INTO country (iso2, name) VALUES ('PW', 'Palau');
INSERT INTO country (iso2, name) VALUES ('PS', 'Palestine');
INSERT INTO country (iso2, name) VALUES ('PA', 'Panama');
INSERT INTO country (iso2, name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO country (iso2, name) VALUES ('PY', 'Paraguay');
INSERT INTO country (iso2, name) VALUES ('PE', 'Peru');
INSERT INTO country (iso2, name) VALUES ('PH', 'Philippines');
INSERT INTO country (iso2, name) VALUES ('PN', 'Pitcairn');
INSERT INTO country (iso2, name) VALUES ('PL', 'Poland');
INSERT INTO country (iso2, name) VALUES ('PT', 'Portugal');
INSERT INTO country (iso2, name) VALUES ('PR', 'Puerto Rico');
INSERT INTO country (iso2, name) VALUES ('QA', 'Qatar');
INSERT INTO country (iso2, name) VALUES ('RE', 'Reunion');
INSERT INTO country (iso2, name) VALUES ('RO', 'Romania');
INSERT INTO country (iso2, name) VALUES ('RU', 'Russian Federation');
INSERT INTO country (iso2, name) VALUES ('RW', 'Rwanda');
INSERT INTO country (iso2, name) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO country (iso2, name) VALUES ('LC', 'Saint Lucia');
INSERT INTO country (iso2, name) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO country (iso2, name) VALUES ('WS', 'Samoa');
INSERT INTO country (iso2, name) VALUES ('SM', 'San Marino');
INSERT INTO country (iso2, name) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO country (iso2, name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO country (iso2, name) VALUES ('SN', 'Senegal');
INSERT INTO country (iso2, name) VALUES ('RS', 'Serbia');
INSERT INTO country (iso2, name) VALUES ('SC', 'Seychelles');
INSERT INTO country (iso2, name) VALUES ('SL', 'Sierra Leone');
INSERT INTO country (iso2, name) VALUES ('SG', 'Singapore');
INSERT INTO country (iso2, name) VALUES ('SK', 'Slovakia');
INSERT INTO country (iso2, name) VALUES ('SI', 'Slovenia');
INSERT INTO country (iso2, name) VALUES ('SB', 'Solomon Islands');
INSERT INTO country (iso2, name) VALUES ('SO', 'Somalia');
INSERT INTO country (iso2, name) VALUES ('ZA', 'South Africa');
INSERT INTO country (iso2, name) VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO country (iso2, name) VALUES ('SS', 'South Sudan');
INSERT INTO country (iso2, name) VALUES ('ES', 'Spain');
INSERT INTO country (iso2, name) VALUES ('LK', 'Sri Lanka');
INSERT INTO country (iso2, name) VALUES ('SH', 'St. Helena');
INSERT INTO country (iso2, name) VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO country (iso2, name) VALUES ('SD', 'Sudan');
INSERT INTO country (iso2, name) VALUES ('SR', 'Suriname');
INSERT INTO country (iso2, name) VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO country (iso2, name) VALUES ('SZ', 'Swaziland');
INSERT INTO country (iso2, name) VALUES ('SE', 'Sweden');
INSERT INTO country (iso2, name) VALUES ('CH', 'Switzerland');
INSERT INTO country (iso2, name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO country (iso2, name) VALUES ('TW', 'Taiwan');
INSERT INTO country (iso2, name) VALUES ('TJ', 'Tajikistan');
INSERT INTO country (iso2, name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO country (iso2, name) VALUES ('TH', 'Thailand');
INSERT INTO country (iso2, name) VALUES ('TG', 'Togo');
INSERT INTO country (iso2, name) VALUES ('TK', 'Tokelau');
INSERT INTO country (iso2, name) VALUES ('TO', 'Tonga');
INSERT INTO country (iso2, name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO country (iso2, name) VALUES ('TN', 'Tunisia');
INSERT INTO country (iso2, name) VALUES ('TR', 'Turkey');
INSERT INTO country (iso2, name) VALUES ('TM', 'Turkmenistan');
INSERT INTO country (iso2, name) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO country (iso2, name) VALUES ('TV', 'Tuvalu');
INSERT INTO country (iso2, name) VALUES ('UG', 'Uganda');
INSERT INTO country (iso2, name) VALUES ('UA', 'Ukraine');
INSERT INTO country (iso2, name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO country (iso2, name) VALUES ('GB', 'United Kingdom');
INSERT INTO country (iso2, name) VALUES ('US', 'United States');
INSERT INTO country (iso2, name) VALUES ('UM', 'United States minor outlying islands');
INSERT INTO country (iso2, name) VALUES ('UY', 'Uruguay');
INSERT INTO country (iso2, name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO country (iso2, name) VALUES ('VU', 'Vanuatu');
INSERT INTO country (iso2, name) VALUES ('VA', 'Vatican City State');
INSERT INTO country (iso2, name) VALUES ('VE', 'Venezuela');
INSERT INTO country (iso2, name) VALUES ('VN', 'Vietnam');
INSERT INTO country (iso2, name) VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO country (iso2, name) VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO country (iso2, name) VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO country (iso2, name) VALUES ('EH', 'Western Sahara');
INSERT INTO country (iso2, name) VALUES ('YE', 'Yemen');
INSERT INTO country (iso2, name) VALUES ('ZM', 'Zambia');
INSERT INTO country (iso2, name) VALUES ('ZW', 'Zimbabwe');

INSERT INTO currency (iso3, symbol, icon, divisible) VALUES ('AUD', '$', '', 100);
INSERT INTO currency (iso3, symbol, icon, divisible) VALUES ('EUR', '€', '', 100);
INSERT INTO currency (iso3, symbol, icon, divisible) VALUES ('GBP', '£', '', 100);
INSERT INTO currency (iso3, symbol, icon, divisible) VALUES ('USD', '$', '', 100);

INSERT INTO data_unit (unit, name, in_bytes) VALUES ('KB', 'Kilobyte', 1024);
INSERT INTO data_unit (unit, name, in_bytes) VALUES ('MB', 'Megabyte', 1048576);
INSERT INTO data_unit (unit, name, in_bytes) VALUES ('GB', 'Gigabyte', 1073741824);
INSERT INTO data_unit (unit, name, in_bytes) VALUES ('TB', 'Terabyte', 1099511627776);

INSERT INTO processor (acronym, name, description, available) VALUES ('cef', 'CEF processor', 'Processes CEF event text', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('ip', 'IP processor', 'Processes event text containing all IP addresses', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('kv', 'KV processor', 'Processes key-value-pair event text that are of the foo=bar variety.', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('json', 'JSON processor', 'Processes JSON event text into structured JSON objects', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('domain', 'Domain processor', 'Processes event text containing all domains', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('email', 'Email processor', 'Processes event text containing all email addresses', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('mac', 'MAC processor', 'Processes event text containing all mac addresses', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('url', 'URL processor', 'Processes event text containing all URLs', true);
INSERT INTO processor (acronym, name, description, available) VALUES ('useragent', 'User-Agent processor', 'Processes event text containing all user-agents', true);

INSERT INTO subscription (model, name, description, details, price_period, price_amount, data_amount, data_excess, enabled, currency_id, data_unit_id) VALUES ('Free', 'Free', 'Limited free usage', '{"features": ["1GB data"], "terms": ["1GB free per month", "Excess data is $5.00 USD per 1GB per month"]}', 'Month', 0, 1073741824, '{"priceAmount": 500, "dataUnitId": 3, "dataAmount": 1073741824}', 1, 4, 3);
INSERT INTO subscription (model, name, description, details, price_period, price_amount, data_amount, data_excess, enabled, currency_id, data_unit_id) VALUES ('Paid', 'Pay-as-you-go', 'Pay only what you use', '{"features": ["Unlimited data"], "terms": ["$4.00 USD per 1GB per month", "No excess"]}', 'Month', 400, 1073741824, '{}', 1, 4, 3);

INSERT INTO marketplace_category (name, tag, description) VALUES ('Detection', 'detection', 'A detection rule.');



